### ISSUE TITLE
Why do we need to pass an non-nil params while Swift accept nil params?

### ISSUE THREAD

**Issue by iambatoan** [hoangta/Oneline#1]
Why do we need to pass an non-nil params while Swift accept nil params? 
For example: font, color, shadowColor, bgColor etc.

**Comment by hoangta** [comment]
There are still some nullables such as UILabel.text, UILabel.attributedText, UITextField.rightView ect..
Either way, those are warpers for the self `itself`, so I decided to keep optionals/non-optional as they are.
